# trigger_training.yaml
# 最终方案：使用Docker镜像，账户B调用，账户A运行

steps:
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID_B}/${_REPOSITORY}/pipeline-executor:latest'
    args:
      - '--project_id=${_PROJECT_ID_A}'
      - '--location=${_LOCATION}'
      - '--pipeline_spec_path=${_PIPELINE_YAML}'
      - '--display_name=heart-disease-training'
      - '--parameter_values={"project_id":"${_PROJECT_ID_A}","data_bucket":"${_DATA_BUCKET}","trainset_filename":"${_TRAINSET}","model_repo":"${_MODEL_BUCKET}"}'

substitutions:
  _PROJECT_ID_A: 'pelagic-pager-472017-v5'        # 账户A：Pipeline运行的地方
  _PROJECT_ID_B: 'de2025-475823'                  # 账户B：Trigger运行的地方
  _LOCATION: 'us-central1'
  _REPOSITORY: 'labrepo'
  _PIPELINE_YAML: 'gs://temp2_de2025_group6/heart_disease_training_pipeline.yaml'
  _DATA_BUCKET: 'data2_de2025_group6'
  _MODEL_BUCKET: 'models2_de2025_group6'
  _TRAINSET: 'Heart_disease_cleveland_new.csv'
  _TEMP_BUCKET: 'temp2_de2025_group6'

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY