# trigger_training.yaml
# 最简单的方式：直接用 gcloud 命令提交 Vertex AI Pipeline

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 提交 Vertex AI Pipeline..."
        cat > /tmp/parameters.json <<EOF
        {
          "project_id": "${_PROJECT_ID}",
          "data_bucket": "${_DATA_BUCKET}",
          "trainset_filename": "${_TRAINSET}",
          "model_repo": "${_MODEL_BUCKET}"
        }
        EOF
        
        gcloud ai pipeline-jobs create \
          --project=${_PROJECT_ID} \
          --region=${_LOCATION} \
          --display-name="heart-disease-$(date +%Y%m%d-%H%M%S)" \
          --template-uri=${_PIPELINE_YAML} \
          --parameter-values-file=/tmp/parameters.json \
          --enable-caching=false

        echo "✅ Pipeline 已提交"


substitutions:
  _LOCATION: 'us-central1'
  _PIPELINE_YAML: 'gs://temp2_de2025_group6/heart_disease_training_pipeline.yaml'
  _DATA_BUCKET: 'data2_de2025_group6'
  _MODEL_BUCKET: 'models2_de2025_group6'
  _TRAINSET: 'Heart_disease_cleveland_new.csv'
  _PROJECT_ID: 'pelagic-pager-472017-v5' 

timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY