steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui:latest'
      - '.'
    dir: 'Part 1/prediction-ui'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui'
    dir: 'Part 1/prediction-ui'

  # Step 3: Deploy prediction-ui with FIXED API URL
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'prediction-ui'
      - '--image=us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=5000'
      - '--set-env-vars=PREDICTOR_API=https://prediction-api-41144114503.us-central1.run.app/heart_predictor/'

images:
  - 'us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/de2025-475823/heart-disease-repo/prediction-ui:latest'

options:
  logging: CLOUD_LOGGING_ONLY